package it.zeze.entity;

// Generated 27-set-2011 15.46.52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * FormazioniId generated by hbm2java
 */
@Embeddable
public class FormazioniId implements java.io.Serializable {

	private int idGiocatore;
	private int idGiornata;
	private int idUtentiFormazioni;
	private int probTitolare;
	private int probPanchina;
	private String note;

	public FormazioniId() {
	}

	public FormazioniId(int idGiocatore, int idGiornata, int idUtentiFormazioni, int probTitolare, int probPanchina) {
		this.idGiocatore = idGiocatore;
		this.idGiornata = idGiornata;
		this.idUtentiFormazioni = idUtentiFormazioni;
		this.probTitolare = probTitolare;
		this.probPanchina = probPanchina;
	}

	public FormazioniId(int idGiocatore, int idGiornata, int idUtentiFormazioni, int probTitolare, int probPanchina, String note) {
		this.idGiocatore = idGiocatore;
		this.idGiornata = idGiornata;
		this.idUtentiFormazioni = idUtentiFormazioni;
		this.probTitolare = probTitolare;
		this.probPanchina = probPanchina;
		this.note = note;
	}

	@Column(name = "id_giocatore", nullable = false)
	public int getIdGiocatore() {
		return this.idGiocatore;
	}

	public void setIdGiocatore(int idGiocatore) {
		this.idGiocatore = idGiocatore;
	}

	@Column(name = "id_giornata", nullable = false)
	public int getIdGiornata() {
		return this.idGiornata;
	}

	public void setIdGiornata(int idGiornata) {
		this.idGiornata = idGiornata;
	}

	@Column(name = "id_utenti_formazioni", nullable = false)
	public int getIdUtentiFormazioni() {
		return this.idUtentiFormazioni;
	}

	public void setIdUtentiFormazioni(int idUtentiFormazioni) {
		this.idUtentiFormazioni = idUtentiFormazioni;
	}

	@Column(name = "prob_titolare", nullable = false)
	public int getProbTitolare() {
		return this.probTitolare;
	}

	public void setProbTitolare(int probTitolare) {
		this.probTitolare = probTitolare;
	}

	@Column(name = "prob_panchina", nullable = false)
	public int getProbPanchina() {
		return this.probPanchina;
	}

	public void setProbPanchina(int probPanchina) {
		this.probPanchina = probPanchina;
	}

	@Column(name = "note", length = 100)
	@Length(max = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormazioniId))
			return false;
		FormazioniId castOther = (FormazioniId) other;

		return (this.getIdGiocatore() == castOther.getIdGiocatore()) && (this.getIdGiornata() == castOther.getIdGiornata()) && (this.getIdUtentiFormazioni() == castOther.getIdUtentiFormazioni()) && (this.getProbTitolare() == castOther.getProbTitolare()) && (this.getProbPanchina() == castOther.getProbPanchina()) && ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null && this.getNote().equals(castOther.getNote())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGiocatore();
		result = 37 * result + this.getIdGiornata();
		result = 37 * result + this.getIdUtentiFormazioni();
		result = 37 * result + this.getProbTitolare();
		result = 37 * result + this.getProbPanchina();
		result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
		return result;
	}

}
