package it.zeze.entity;

// Generated 27-set-2011 15.46.52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Giornate generated by hbm2java
 */
@Entity
@Table(name = "giornate", catalog = "fanta_formazione")
public class Giornate implements java.io.Serializable {

	private int id;
	private Date data;
	private Set<Statistiche> statistiches = new HashSet<Statistiche>(0);
	private Set<ProbabiliFormazioniFg> probabiliFormazioniFgs = new HashSet<ProbabiliFormazioniFg>(0);
	private Set<Formazioni> formazionis = new HashSet<Formazioni>(0);
	private Set<ProbabiliFormazioniGazzetta> probabiliFormazioniGazzettas = new HashSet<ProbabiliFormazioniGazzetta>(0);
	private Set<Calendario> calendarios = new HashSet<Calendario>(0);

	public Giornate() {
	}

	public Giornate(int id) {
		this.id = id;
	}

	public Giornate(int id, Date data, Set<Statistiche> statistiches, Set<ProbabiliFormazioniFg> probabiliFormazioniFgs, Set<Formazioni> formazionis, Set<ProbabiliFormazioniGazzetta> probabiliFormazioniGazzettas, Set<Calendario> calendarios) {
		this.id = id;
		this.data = data;
		this.statistiches = statistiches;
		this.probabiliFormazioniFgs = probabiliFormazioniFgs;
		this.formazionis = formazionis;
		this.probabiliFormazioniGazzettas = probabiliFormazioniGazzettas;
		this.calendarios = calendarios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<Statistiche> getStatistiches() {
		return this.statistiches;
	}

	public void setStatistiches(Set<Statistiche> statistiches) {
		this.statistiches = statistiches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<ProbabiliFormazioniFg> getProbabiliFormazioniFgs() {
		return this.probabiliFormazioniFgs;
	}

	public void setProbabiliFormazioniFgs(Set<ProbabiliFormazioniFg> probabiliFormazioniFgs) {
		this.probabiliFormazioniFgs = probabiliFormazioniFgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<Formazioni> getFormazionis() {
		return this.formazionis;
	}

	public void setFormazionis(Set<Formazioni> formazionis) {
		this.formazionis = formazionis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<ProbabiliFormazioniGazzetta> getProbabiliFormazioniGazzettas() {
		return this.probabiliFormazioniGazzettas;
	}

	public void setProbabiliFormazioniGazzettas(Set<ProbabiliFormazioniGazzetta> probabiliFormazioniGazzettas) {
		this.probabiliFormazioniGazzettas = probabiliFormazioniGazzettas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<Calendario> getCalendarios() {
		return this.calendarios;
	}

	public void setCalendarios(Set<Calendario> calendarios) {
		this.calendarios = calendarios;
	}

}
