package it.zeze.entity;

// Generated 27-set-2011 15.46.52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Utenti generated by hbm2java
 */
@Entity
@Table(name = "utenti", catalog = "fanta_formazione")
public class Utenti implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private Set<UtentiFormazioni> utentiFormazionis = new HashSet<UtentiFormazioni>(0);

	public Utenti() {
	}

	public Utenti(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public Utenti(int id, String username, String password, Set<UtentiFormazioni> utentiFormazionis) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.utentiFormazionis = utentiFormazionis;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utenti")
	public Set<UtentiFormazioni> getUtentiFormazionis() {
		return this.utentiFormazionis;
	}

	public void setUtentiFormazionis(Set<UtentiFormazioni> utentiFormazionis) {
		this.utentiFormazionis = utentiFormazionis;
	}

}
