package it.zeze.entity;

// Generated 27-set-2011 15.46.52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * UtentiFormazioni generated by hbm2java
 */
@Entity
@Table(name = "utenti_formazioni", catalog = "fanta_formazione")
public class UtentiFormazioni implements java.io.Serializable {

	private int id;
	private Utenti utenti;
	private String nomeFormazione;
	private Set<Formazioni> formazionis = new HashSet<Formazioni>(0);

	public UtentiFormazioni() {
	}

	public UtentiFormazioni(int id, Utenti utenti, String nomeFormazione) {
		this.id = id;
		this.utenti = utenti;
		this.nomeFormazione = nomeFormazione;
	}

	public UtentiFormazioni(int id, Utenti utenti, String nomeFormazione, Set<Formazioni> formazionis) {
		this.id = id;
		this.utenti = utenti;
		this.nomeFormazione = nomeFormazione;
		this.formazionis = formazionis;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utente", nullable = false)
	@NotNull
	public Utenti getUtenti() {
		return this.utenti;
	}

	public void setUtenti(Utenti utenti) {
		this.utenti = utenti;
	}

	@Column(name = "nome_formazione", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getNomeFormazione() {
		return this.nomeFormazione;
	}

	public void setNomeFormazione(String nomeFormazione) {
		this.nomeFormazione = nomeFormazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utentiFormazioni")
	public Set<Formazioni> getFormazionis() {
		return this.formazionis;
	}

	public void setFormazionis(Set<Formazioni> formazionis) {
		this.formazionis = formazionis;
	}

}
